- hosts: all
  become: true
  strategy: free
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
      autoremove: yes
    tags:
      - updates
  - name: journal cleanup
    shell:
      cmd: journalctl --vacuum-size=1024000 
    changed_when: False
    tags:
      - cleanup 
