- hosts: all
  become: true
  strategy: free
  tasks:
  - name: create ssh_users group
    ansible.builtin.group:
      name: ssh_users
      state: present
  - name: add ali to ssh_users
    ansible.builtin.user:
      name: ali
      groups: ssh_users
      state: present
      
  - name: Copy ssh user
    copy:
      src: app/sshd_config.j2
      dest: /etc/ssh/sshd_config
  
  - name: restart ssh
    ansible.builtin.service:
      name: ssh
      state: restarted

  - name: install needed packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
      - uidmap
      - zsh
      - git
      - prometheus-node-exporter
