- hosts: all:!offlines
  become: true
  strategy: free
  tasks:
  - name: create ssh_users group
    ansible.builtin.group:
      name: ssh_users
      state: present
  - name: add ali to ssh_users
    ansible.builtin.user:
      name: ali
      groups: ssh_users
      state: present

  - name: Copy ssh user
    ansible.builtin.copy:
      src: app/sshd_config.j2
      dest: /etc/ssh/sshd_config
      mode: "0641"

  - name: restart ssh
    ansible.builtin.service:
      name: ssh
      state: restarted

  - name: install needed packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
      - uidmap
      - zsh
      - git
      - prometheus-node-exporter
      - acl
  - name: copy osquery to server
    ansible.builtin.copy:
      src: debs/
      dest: /tmp/debs
      mode: 0700
    tags: this
  - name: install osquery
    ansible.builtin.apt:
      deb: "/tmp/debs/{{ item }}.deb"
    with_items:
      - osquery
      - splunkforwarder
    tags: this
